%%
%% Autogenerated by Thrift Compiler (0.9.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("hive_metastore_types.hrl").

-define(hive_metastore_DDL_TIME, "transient_lastDdlTime").

-define(hive_metastore_IS_ARCHIVED, "is_archived").

-define(hive_metastore_ORIGINAL_LOCATION, "original_location").

-define(hive_metastore_META_TABLE_COLUMNS, "columns").

-define(hive_metastore_META_TABLE_COLUMN_TYPES, "columns.types").

-define(hive_metastore_BUCKET_FIELD_NAME, "bucket_field_name").

-define(hive_metastore_BUCKET_COUNT, "bucket_count").

-define(hive_metastore_FIELD_TO_DIMENSION, "field_to_dimension").

-define(hive_metastore_META_TABLE_NAME, "name").

-define(hive_metastore_META_TABLE_DB, "db").

-define(hive_metastore_META_TABLE_LOCATION, "location").

-define(hive_metastore_META_TABLE_SERDE, "serde").

-define(hive_metastore_META_TABLE_PARTITION_COLUMNS, "partition_columns").

-define(hive_metastore_FILE_INPUT_FORMAT, "file.inputformat").

-define(hive_metastore_FILE_OUTPUT_FORMAT, "file.outputformat").

-define(hive_metastore_META_TABLE_STORAGE, "storage_handler").

