%%
%% Autogenerated by Thrift Compiler (0.9.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(hive_metastore_types).

-include("hive_metastore_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('version') ->
  {struct, [{1, string},
          {2, string}]}
;

struct_info('fieldSchema') ->
  {struct, [{1, string},
          {2, string},
          {3, string}]}
;

struct_info('type') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}}]}
;

struct_info('hiveObjectRef') ->
  {struct, [{1, i32},
          {2, string},
          {3, string},
          {4, {list, string}},
          {5, string}]}
;

struct_info('privilegeGrantInfo') ->
  {struct, [{1, string},
          {2, i32},
          {3, string},
          {4, i32},
          {5, bool}]}
;

struct_info('hiveObjectPrivilege') ->
  {struct, [{1, {struct, {'hive_metastore_types', 'hiveObjectRef'}}},
          {2, string},
          {3, i32},
          {4, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}]}
;

struct_info('privilegeBag') ->
  {struct, [{1, {list, {struct, {'hive_metastore_types', 'hiveObjectPrivilege'}}}}]}
;

struct_info('principalPrivilegeSet') ->
  {struct, [{1, {map, string, {list, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}}},
          {2, {map, string, {list, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}}},
          {3, {map, string, {list, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}}}]}
;

struct_info('role') ->
  {struct, [{1, string},
          {2, i32},
          {3, string}]}
;

struct_info('database') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, {map, string, string}},
          {5, {struct, {'hive_metastore_types', 'principalPrivilegeSet'}}}]}
;

struct_info('serDeInfo') ->
  {struct, [{1, string},
          {2, string},
          {3, {map, string, string}}]}
;

struct_info('order') ->
  {struct, [{1, string},
          {2, i32}]}
;

struct_info('storageDescriptor') ->
  {struct, [{1, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}},
          {2, string},
          {3, string},
          {4, string},
          {5, bool},
          {6, i32},
          {7, {struct, {'hive_metastore_types', 'serDeInfo'}}},
          {8, {list, string}},
          {9, {list, {struct, {'hive_metastore_types', 'order'}}}},
          {10, {map, string, string}}]}
;

struct_info('table') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, i32},
          {5, i32},
          {6, i32},
          {7, {struct, {'hive_metastore_types', 'storageDescriptor'}}},
          {8, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}},
          {9, {map, string, string}},
          {10, string},
          {11, string},
          {12, string},
          {13, {struct, {'hive_metastore_types', 'principalPrivilegeSet'}}}]}
;

struct_info('partition') ->
  {struct, [{1, {list, string}},
          {2, string},
          {3, string},
          {4, i32},
          {5, i32},
          {6, {struct, {'hive_metastore_types', 'storageDescriptor'}}},
          {7, {map, string, string}},
          {8, {struct, {'hive_metastore_types', 'principalPrivilegeSet'}}}]}
;

struct_info('index') ->
  {struct, [{1, string},
          {2, string},
          {3, string},
          {4, string},
          {5, i32},
          {6, i32},
          {7, string},
          {8, {struct, {'hive_metastore_types', 'storageDescriptor'}}},
          {9, {map, string, string}},
          {10, bool}]}
;

struct_info('schema') ->
  {struct, [{1, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}},
          {2, {map, string, string}}]}
;

struct_info('metaException') ->
  {struct, [{1, string}]}
;

struct_info('unknownTableException') ->
  {struct, [{1, string}]}
;

struct_info('unknownDBException') ->
  {struct, [{1, string}]}
;

struct_info('alreadyExistsException') ->
  {struct, [{1, string}]}
;

struct_info('invalidObjectException') ->
  {struct, [{1, string}]}
;

struct_info('noSuchObjectException') ->
  {struct, [{1, string}]}
;

struct_info('indexAlreadyExistsException') ->
  {struct, [{1, string}]}
;

struct_info('invalidOperationException') ->
  {struct, [{1, string}]}
;

struct_info('configValSecurityException') ->
  {struct, [{1, string}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('version') ->
  {struct, [{1, undefined, string, 'version', undefined},
          {2, undefined, string, 'comments', undefined}]}
;

struct_info_ext('fieldSchema') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, string, 'type', undefined},
          {3, undefined, string, 'comment', undefined}]}
;

struct_info_ext('type') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, optional, string, 'type1', undefined},
          {3, optional, string, 'type2', undefined},
          {4, optional, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}, 'fields', []}]}
;

struct_info_ext('hiveObjectRef') ->
  {struct, [{1, undefined, i32, 'objectType', undefined},
          {2, undefined, string, 'dbName', undefined},
          {3, undefined, string, 'objectName', undefined},
          {4, undefined, {list, string}, 'partValues', []},
          {5, undefined, string, 'columnName', undefined}]}
;

struct_info_ext('privilegeGrantInfo') ->
  {struct, [{1, undefined, string, 'privilege', undefined},
          {2, undefined, i32, 'createTime', undefined},
          {3, undefined, string, 'grantor', undefined},
          {4, undefined, i32, 'grantorType', undefined},
          {5, undefined, bool, 'grantOption', undefined}]}
;

struct_info_ext('hiveObjectPrivilege') ->
  {struct, [{1, undefined, {struct, {'hive_metastore_types', 'hiveObjectRef'}}, 'hiveObject', #hiveObjectRef{}},
          {2, undefined, string, 'principalName', undefined},
          {3, undefined, i32, 'principalType', undefined},
          {4, undefined, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}, 'grantInfo', #privilegeGrantInfo{}}]}
;

struct_info_ext('privilegeBag') ->
  {struct, [{1, undefined, {list, {struct, {'hive_metastore_types', 'hiveObjectPrivilege'}}}, 'privileges', []}]}
;

struct_info_ext('principalPrivilegeSet') ->
  {struct, [{1, undefined, {map, string, {list, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}}, 'userPrivileges', dict:new()},
          {2, undefined, {map, string, {list, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}}, 'groupPrivileges', dict:new()},
          {3, undefined, {map, string, {list, {struct, {'hive_metastore_types', 'privilegeGrantInfo'}}}}, 'rolePrivileges', dict:new()}]}
;

struct_info_ext('role') ->
  {struct, [{1, undefined, string, 'roleName', undefined},
          {2, undefined, i32, 'createTime', undefined},
          {3, undefined, string, 'ownerName', undefined}]}
;

struct_info_ext('database') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, string, 'description', undefined},
          {3, undefined, string, 'locationUri', undefined},
          {4, undefined, {map, string, string}, 'parameters', dict:new()},
          {5, optional, {struct, {'hive_metastore_types', 'principalPrivilegeSet'}}, 'privileges', #principalPrivilegeSet{}}]}
;

struct_info_ext('serDeInfo') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, string, 'serializationLib', undefined},
          {3, undefined, {map, string, string}, 'parameters', dict:new()}]}
;

struct_info_ext('order') ->
  {struct, [{1, undefined, string, 'col', undefined},
          {2, undefined, i32, 'order', undefined}]}
;

struct_info_ext('storageDescriptor') ->
  {struct, [{1, undefined, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}, 'cols', []},
          {2, undefined, string, 'location', undefined},
          {3, undefined, string, 'inputFormat', undefined},
          {4, undefined, string, 'outputFormat', undefined},
          {5, undefined, bool, 'compressed', undefined},
          {6, undefined, i32, 'numBuckets', undefined},
          {7, undefined, {struct, {'hive_metastore_types', 'serDeInfo'}}, 'serdeInfo', #serDeInfo{}},
          {8, undefined, {list, string}, 'bucketCols', []},
          {9, undefined, {list, {struct, {'hive_metastore_types', 'order'}}}, 'sortCols', []},
          {10, undefined, {map, string, string}, 'parameters', dict:new()}]}
;

struct_info_ext('table') ->
  {struct, [{1, undefined, string, 'tableName', undefined},
          {2, undefined, string, 'dbName', undefined},
          {3, undefined, string, 'owner', undefined},
          {4, undefined, i32, 'createTime', undefined},
          {5, undefined, i32, 'lastAccessTime', undefined},
          {6, undefined, i32, 'retention', undefined},
          {7, undefined, {struct, {'hive_metastore_types', 'storageDescriptor'}}, 'sd', #storageDescriptor{}},
          {8, undefined, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}, 'partitionKeys', []},
          {9, undefined, {map, string, string}, 'parameters', dict:new()},
          {10, undefined, string, 'viewOriginalText', undefined},
          {11, undefined, string, 'viewExpandedText', undefined},
          {12, undefined, string, 'tableType', undefined},
          {13, optional, {struct, {'hive_metastore_types', 'principalPrivilegeSet'}}, 'privileges', #principalPrivilegeSet{}}]}
;

struct_info_ext('partition') ->
  {struct, [{1, undefined, {list, string}, 'values', []},
          {2, undefined, string, 'dbName', undefined},
          {3, undefined, string, 'tableName', undefined},
          {4, undefined, i32, 'createTime', undefined},
          {5, undefined, i32, 'lastAccessTime', undefined},
          {6, undefined, {struct, {'hive_metastore_types', 'storageDescriptor'}}, 'sd', #storageDescriptor{}},
          {7, undefined, {map, string, string}, 'parameters', dict:new()},
          {8, optional, {struct, {'hive_metastore_types', 'principalPrivilegeSet'}}, 'privileges', #principalPrivilegeSet{}}]}
;

struct_info_ext('index') ->
  {struct, [{1, undefined, string, 'indexName', undefined},
          {2, undefined, string, 'indexHandlerClass', undefined},
          {3, undefined, string, 'dbName', undefined},
          {4, undefined, string, 'origTableName', undefined},
          {5, undefined, i32, 'createTime', undefined},
          {6, undefined, i32, 'lastAccessTime', undefined},
          {7, undefined, string, 'indexTableName', undefined},
          {8, undefined, {struct, {'hive_metastore_types', 'storageDescriptor'}}, 'sd', #storageDescriptor{}},
          {9, undefined, {map, string, string}, 'parameters', dict:new()},
          {10, undefined, bool, 'deferredRebuild', undefined}]}
;

struct_info_ext('schema') ->
  {struct, [{1, undefined, {list, {struct, {'hive_metastore_types', 'fieldSchema'}}}, 'fieldSchemas', []},
          {2, undefined, {map, string, string}, 'properties', dict:new()}]}
;

struct_info_ext('metaException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('unknownTableException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('unknownDBException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('alreadyExistsException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('invalidObjectException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('noSuchObjectException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('indexAlreadyExistsException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('invalidOperationException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('configValSecurityException') ->
  {struct, [{1, undefined, string, 'message', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

